logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.elasticsearch.hosts: [ "https://elasticsearch-master:9200" ]

logstashPipeline:
  logstash.conf: |
    input {
      http {
        port => 5044
        codec => json
      }
      tcp {
        port => 5043
        codec => json
      }
    }
    
    filter {
      date {
        match => ["timestamp","ISO8601"]
        remove_field => ["timestamp"]
      }
      mutate {
        coerce => {
          "user_id" => "integer"
          "robot_id" => "integer"
        }
        remove_field => ["@version"]
      }
      if ![index] {
        mutate {
          add_field => { "index" => "unknown" }
        }
      }
    }
    
    output {
      elasticsearch {
        ssl => true
        ssl_certificate_verification => false
        hosts => ["https://elasticsearch-master:9200"]
        user => "elastic"
        password => "xxx"
        index => "%{[index]}-%{+YYYY.MM.dd}"
      }
    }

service:
  ports:
    - name: http
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: tcp
      port: 5043
      protocol: TCP
      targetPort: 5043