logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.elasticsearch.hosts: [ "https://elasticsearch-master:9200" ]

logstashPipeline:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    
    filter {
      date {
        match => [ "timestamp", "ISO8601" ]
      }
      if ![index] {
        mutate {
          add_field => { "index" => "unknown" }
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "%{[index]}-%{+YYYY.MM.dd}"
      }
    }